# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userActivity', '0002_auto_20180418_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='login',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='logout',
            field=models.CharField(max_length=200),
        ),
    ]
