# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userActivity', '0005_auto_20180420_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logout',
            field=models.DateTimeField(blank=True),
        ),
    ]
