# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userActivity', '0008_post_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='login',
        ),
        migrations.RemoveField(
            model_name='post',
            name='logout',
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(default=1000, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userActivity.Post'),
        ),
    ]
