# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userActivity', '0009_auto_20180420_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
