# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userActivity', '0011_auto_20180420_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='loginDuration',
            field=models.BigIntegerField(null=True),
        ),
    ]
