# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 07:19
from __future__ import unicode_literals

from django.db import migrations

def create_initial_products(apps, schema_editor):
    Users = apps.get_model('userActivity', 'Post')

    Users(user_id='123126',name='vagupta',password = 'vagupta').save()
    Users(user_id='123127',name='mayagra',password = 'mayagra').save()
    Users(user_id='123128',name='g10work',password = 'g10work').save()


class Migration(migrations.Migration):

    dependencies = [
        ('userActivity', '0012_activity_loginduration'),
    ]

    operations = [
            migrations.RunPython(create_initial_products),

    ]
